version: '3.7'
services:
  website:
    build: .
    environment:
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/website
      - ./website/node_modules
    command: ["npm", "run", "dev"]
